name: Build Typst document (CI)
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            examples/exam-001.typ
            examples/exam-002.typ
            examples/exam-minimal.typ

      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: *.pdf

      # - name: Get current date
      #   id: date
      #   run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: github.ref_type == 'tag'
      #   with:
      #     name: "${{ github.ref_name }} â€” ${{ env.DATE }}"
      #     files: main.pdf